### PR TITLE
phoenix_download.R (fixes #13)

### LINKED ISSUE #12: Trouble downloading Phoenix — probably a bug in dw_file function
So download_phoenix fails.

The problem is in this piece code (currently line 41):

``` R
filename <- gsub(baseurl, "", link)
```

`filename` value in this case will be for example `/path/to/destpath/https://s3.amazonaws.com/openeventdata/current/events.full.20140410.txt.zip` which necessarily raises an exception.

I'm afraid the problem is that `baseurl` as a regexp doesn't match itself as a string. I'll try to provide a pull request with a fix in the following days.

### PR DESCRIPTION
**Pull request by roveo**
**The code was tested on Mac OS X only (should work in Linux). Please test it on Windows before merging.**

The main idea is that when you extract filename from URL it shouldn't depend on any hardcoded base URLs (in case they change again).
- `get_links` is now the only place that logically needs `phoenix_version` parameter, all the other functions just pass it there
- `file_dw` doesn't depend on any particular URL or filename scheme, just must have `.zip` in the end
- the code is now less dependent on the correct user input, like it automatically adds trailing `/` to paths and `v` in the beginning of `phoenix_version` if it's not there
- now it doesn't directly import any packages into the global namespace
- generally it uses standard packages instead of external (like `RCurl`)

### CODE REVIEW

**Comment by roveo** [comment]
OK, so we found out there's a problem with Windows paths.

The code goes like this: if there's no `/` or `\` in the end of the path, it is added. The character is determined by `.Platform$file.path` variable.

I'll be able to check on Monday, but I think the problem is that Windows paths in R have double separators (`\\`), because `\` is an escape character. So on Windows you have to add `\\` to the path.

**Comment by roveo** [comment]
So no, the path separator on Windows is the same, but on Windows `unzip` doesn't work if `destpath` has a trailing separator (which my code added). On Linux it seems to be working both ways, so now istead of adding the separator the code _removes_ it.

`C:/lalala/phoxy_test` is OK, `C:/lalala/phoxy_test/` isn't.

And Windows usually doesn't have `curl` installed, so `method = 'curl'` for `download.file` doesn't work. But `method = 'auto'` doesn't work with Unix, so now the method is set based on `.Platform$OS.type` env variable.

**Comment by roveo** [comment]
Fixed Windows line-ending in the file, to see normal diff, refer to https://github.com/roveo/phoxy/commit/6075d468009ae66d2416ad1123e5d7ad211ece9a

**Comment by ahalterman** [comment]
Hey @roveo, I'm comfortable merging the PR in without any further testing on Windows. It'll definitely be better in any case that what's already there. There are some merge conflicts now. Can you rebase your branch and resolve conflicts?

Thanks again for the great contributions.

**Comment by roveo** [comment]
@ahalterman that was tricky, because I already merged `phoenix_download#12` to my fork's master. Had to hard reset it, then rebase. I guess it worked, but there's twice as many commits in this branch now. I'm not that good with more complicated git usage.

**Comment by roveo** [comment]
Okay, now I performed [this](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) kind of rebase, hope it's better.

**Comment by ahalterman** [comment]
Thanks again! Everything looks good here.

**Pull request merged**
